{
 "title": "Main",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LSC",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/logtogether/LogTogether.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Worst time to tick",
   "type": "barchart",
   "description": "Grouped by multiblock type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time({logtype=\"LAG WARNING:\"} | line_format `{{.message}}` | regexp `(?P<classname>.+) took (?P<ticktime>[0-9\\.]+us) ` | unwrap duration(ticktime) [$__interval]) by (classname)",
     "legendFormat": "{{classname}}"
    }
   ]
  },
  {
   "title": "Average time to tick from logged spikes",
   "type": "barchart",
   "description": "Grouped by multiblock type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time({logtype=\"LAG WARNING:\"} | line_format `{{.message}}` | regexp `(?P<classname>.+) took (?P<ticktime>[0-9\\.]+us) ` | unwrap duration(ticktime) [$__interval]) by (classname)",
     "legendFormat": "{{classname}}"
    }
   ]
  },
  {
   "title": "Amount of logged ticks",
   "type": "barchart",
   "description": "Grouped by multiblock type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(classname) (count_over_time({logtype=\"LAG WARNING:\"} | line_format `{{.message}}` | regexp `(?P<classname>.+) took (?P<ticktime>[0-9\\.]+us) ` [$__interval]))",
     "legendFormat": "{{classname}}"
    }
   ]
  },
  {
   "title": "LSC Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "repeat": "LSC",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time({logtype=\"LSC STORAGE:\"} | regexp `(?P<storage_amount>\\d+) on LSC at (?P<coordinates>[-\\d,]+) in dimension (?P<dimension>\\d+)` | label_format lsc_id=\"{{.coordinates}} in dimension {{.dimension}}\" | lsc_id = `$LSC` | unwrap storage_amount [$__interval]) by (lsc_id)"
    }
   ]
  },
  {
   "title": "MultiBlock Shutdowns",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{logtype=\"MULTIBLOCK SHUTDOWN:\"} | line_format `{{.time}} {{.message}}`",
     "maxLines": 500
    }
   ]
  }
 ]
}