server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # dummy URL, no real backend for now

scrape_configs:
  - job_name: LogTogether
    static_configs:
      - targets:
          - localhost
        labels:
          job: logtogether
          __path__: /var/log/logtogether/LogTogether.log
    pipeline_stages:
      - regex:
          expression: '\[(?P<time>[^\]]+)] \[(?P<thread>[^/]+)/(?P<level>[^\]]+)] \[(?P<logger>[^/]+)/]: (?P<message>.+)'
      - labels:
          level: ""
          thread: ""
          logger: ""
      - timestamp:
          source: time
          format: "2006-01-02 15:04:05"